# dotnet 2.2 issue: https://travis-ci.community/t/dotnet-core-2-2/1216/11

language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

notifications:
  email: false

script:
 - dotnet restore
 - dotnet build
 - dotnet test
